// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.1_db0@0.3.1_eslint@9.24.0_jiti@2.4.2__ioredis@5.6.0_lightning_lpyvg7hxwlxeo4rfp6fwvd57ai/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@1.11.0_magicast@0.3.5_vite@6.2.5_jiti@2.4.2_lightningcss@1.29.2_terser@5.39.0_yaml_swzfx4twcm3m3t567qraejoxci/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}