server:
  port: 8000
cn:
  xilio:
    turtle:
      upload:
        #path: /Users/liuxin/Desktop/turtle/tmp #文件上传根路径 如果没有配置会根据操作系统提供一个默认的
        allowed-extensions: [ jpg, png, pdf,ico,jpeg ]
      api:
        prefix: /api
spring:
  profiles:
    active: mysql # 激活的配置文件
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB #最大文件
      max-request-size: 10MB #最大文件请求大小
      enabled: false # 关闭 multipart 支持
  webflux:
    format:
      date-time: yyyy/MM/dd HH:mm:ss
      date: yyyy/MM/dd
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 600
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  token-prefix: Bearer
logging:
  level:
    #    root: debug
    #    org.springframework: debug
    cn.xilio.turtle: debug
